server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password: